name: CI/CD Pipeline

on: push

env:
  ARTIFACT_NAME: result

jobs:
    job1:
        name: Test
        runs-on: Ubuntu-latest
        steps:
            - name: Step 1
              uses: actions/checkout@v4

            - name: step 2
              run: python hello.py
  
    job2:
        name: Build
        needs: job1
        runs-on: Ubuntu-latest
        steps:
            - name: Step 1
              uses: actions/checkout@v4

            - name: Step 2
              uses: actions/upload-artifact@v2
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: .
              


